env:
  browser: true
  node: true
  jest: true
  es6: true

extends:
  - eslint:recommended
  - llama
  - prettier
  - plugin:react/recommended

plugins:
  - react

parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true

rules:
  require-jsdoc: off
