extends:
  - freighter-repo
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint

overrides:
  - files: '**/__tests__/*.ts{x,}'
    rules:
      '@typescript-eslint/no-explicit-any': off
  - files: '**/*.js'
    rules:
      '@typescript-eslint/no-var-requires': off

parser: '@typescript-eslint/parser'

globals:
  SyntheticMouseEvent: readonly
  SyntheticInputEvent: readonly
  $Call: readonly

rules:
  no-prototype-builtins: off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-empty-function': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-unused-vars': error
