name: Continuous Integration

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12, 14]
    name: Node ${{ matrix.node_version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        name: install node v${{ matrix.node_version }}
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install packages
        run: yarn install --color
      - name: Run tests
        run: yarn ci
      - name: Compile app
        run: |
          cd packages/ponder-desktop
          yarn build
